services:
  backend:
    build:
      context: ./backend
    container_name: backend
    platform: linux/amd64
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    platform: linux/amd64
    ports:
      - "80:80"

